Polyconseil/django-mds

mds/management/commands/genfixture.py, mds/models.py, mds/views.py
Now we can build a list of devices with telemetry in other contexts (ES export in my case).
=> Refactor queryset to reuse latest_telemetry field

mds/apis/agency_api/v0_x/vehicles.py, mds/apis/prv_api/vehicles.py, mds/enums.py, mds/factories.py, mds/locale/en_US/LC_MESSAGES/django.po, mds/locale/fr_FR/LC_MESSAGES/django.po, mds/migrations/0001_initial.py, mds/models.py, tests/apis/agency_api/v0_x/test_devices.py
Now in python 3 it is considered better style to use python enums,
and adapt them to Django or DRF  choices when necessary.
Also, added context to translations to avoid cumbersome rework in the future.
=> enums: use python Enum

CHANGELOG.rst, mds/apis/utils.py, mds/management/commands/poll_providers.py, mds/utils.py, tests/test_utils.py
The implementation was wrong. `timedelta.total_seconds()` has
microsecond accuracy. Multiplied by 1000, we had a number of
milliseconds. But the implementation added `td.microseconds / 1000`,
which was wrong. A similarly correct implementation was:
td = value - datetime.datetime(1970, 1, 1, tzinfo=datetime.timezone.utc)
return round(td.total_seconds() * 1000)
... but `round(value.timestamp() * 1000)` is shorter.
=> apis: Fix UnixTimestampMilliseconds.to_representation

CHANGELOG.rst, mds/management/commands/poll_providers.py
When there was no status changes, `process_status_changes()` would
raise an error when trying:
max(status_change["event_time"] for status_change in status_changes)
... because `max` cannot be called on an empty sequence.
=> poll_providers: Don't raise an error if there is no status changes

CHANGELOG.rst, mds/management/commands/poll_providers.py
Don't fail and rollback the whole batch when only one item is rotten.
This also means we won't ever come back to invalid events when they are
fixed, since we won't try again next time.
Good idea?
Wait for the sandbox to fix its mess before merging that for "production" providers we'll poll?
=> poll_providers: don't reject the whole batch on validation

CHANGELOG.rst, mds/management/commands/poll_providers.py
We were expecting an empty response from the provider, but not an empty
subset of valid data.
=> poll_providers: fix empty status_changes after validating

CHANGELOG.rst, mds/apis/prv_api/vehicles.py, tests/apis/prv_api/test_vehicles.py
- use the dn value in device model rather than doing a query on latest event
=> Fix slowness when retrieving device

CHANGELOG.rst, mds/apis/agency_api/v0_x/vehicles.py
- in the Device table, in properties dict field, and then in telemetry, the battery field name should have been "battery_pct"
- It was changed after, and now we have two conflicting namings in base. We have to fix that too
=> Fix saving in base with wrong name for battery field in device telemetry

CHANGELOG.rst, prerelease_script.py, setup.cfg
- Translations were not working because no compilemessages command was ever run to generate the .mo files from the .po files
=> Fix translations which were not working

mds/management/commands/poll_providers.py
As this already happened...
The more I add these validations, the more I feel like I'm reinventing
DRF validators, or at least Django forms...
=> poll_providers: also expect timestamps to be strings

CHANGELOG.rst, mds/apis/agency_api/v0_x/vehicles.py, mds/management/commands/poll_providers.py, mds/utils.py
The ones pushed by the provider have precedence.
The drawback over bulk_create is that we don't get the created objects in return.
=> utils: single upsert command for creating event records

CHANGELOG.rst, mds/access_control/stateless_jwt.py
I've tested it, and it seems to work.
- when I used the correct access_token, my export was working (it's working !)
- when using a wrong token, i was denied the access.
=> Add token authentication using browser url

mds/management/commands/poll_providers.py
As UUID and str never matched, we would try to create the same devices
again and again... Hopefully we had a "ON CONFLICT DO NOTHING" but that
was a waste of resources.
=> poll_providers: fix comparing missing device UIDs

mds/management/commands/poll_providers.py
I had a strange bug where my provider changes were not taken into
account, or quickly reverted to the old value.
It took me some time to realize the poller was running like crazy after
the full reset, and Django "save()" will dump the full state in memory
to the database.
=> poll_providers: only update the field changed

mds/management/commands/poll_providers.py, mds/server/settings.py
Indeed we were caching the token for the life of the polling session,
but as a cron job, a new session was started every minute or so...
The token is considered as a password and is encrypted. Not with 
Django's secret key, the required key is a particular format.
Host applications are free to choose the cache of their choice.
=> poll_providers: persist token in Django cache

CHANGELOG.rst, mds/apis/prv_api/provider_api.py, mds/apis/prv_api/urls.py, tests/apis/prv_api/test_status_changes.py
Based on MDS provider API spec (https://github.com/CityOfLosAngeles/mobility-data-specification/tree/dev/provider)
expose an aggregated API (events from all providers).
This makes django-mds pluggable with external services that need
raw data.
For now only `status_change` endpoint is implemented.
=> prv_api: add a provider_api

setup.cfg
the binary version should not be required anymore @ 2.9.
=> pythhon dependencies: use non binary psycopg

CHANGELOG.rst, mds/apis/prv_api/urls.py
MDS spec does not enforce a trailing slash for "status_changes" endpoint.
We don't want either to forbid it.
=> prv_api: make DRF trailing slash optional

mds/apis/agency_api/v0_x/vehicles.py, mds/provider_poller/poller.py, tests/apis/agency_api/v0_x/test_devices.py, tests/management/commands/test_poll_providers.py
The goal was to simulate device registration when we catch up with a provider history.
=> move fake register event from agency API to poller

CHANGELOG.rst, mds/provider_poller/poller.py, mds/provider_poller/settings.py
When first polling a provider, we usually don't want all
data from the dawn of times.
90 days is the default. Setting None is still an option to
retrieve everything.
=> provider_poller: limit initial polling

mds/provider_poller/oauth2_store.py, mds/provider_poller/settings.py, mds/server/settings.py
Settings in the MDS server were of no help for projects hosting mds.
TODO: We're partly reinventing appconf here, check it out later.
=> poller: reuse the new settings module for defaults

mds/apis/prv_api/vehicles.py
Due to differences in the `typing` module between 3.6 & 3.7,
`drf-yasg`'s `SerializerMethodFieldInspector` stopped working as
expected with type hints.
$ python3.6 -c "import inspect, typing;print(inspect.isclass(typing.List))"
True
$ python3.7 -c "import inspect, typing;print(inspect.isclass(typing.List))"
False
Let's use `swagger_serializer_method` method instead.
=> prv_api: fix schema generation in 3.7

CHANGELOG.rst, mds/apis/prv_api/urls.py, tests/apis/prv_api/test_status_changes.py
commit 00ac141 was supposed to make trailing `/` optional
but a redirection was actually made when omitting it.
As DRF casts initial trailing_slash argument as a boolean
(https://github.com/encode/django-rest-framework/blob/afb678433b7dc068213e6e8a359ad1f6fff05b0d/rest_framework/routers.py#L148)
we need to set it as a regex after router initialization
=> prv_api: fix trailing slash option

mds/provider_poller/poller.py
As the reworked comment at the top of the diff says, polling by
timestamp brings the issue of ignoring old telemetries saved in the
provider database after we already polled that point in time.
Better order by "saved_at" (as we call it in EventRecord) if the
provider API supports it.
When we activate that param in the API configuration, we also need to
reset the "last_start_time_polled" field.
=> provider_poller: support alternative time field

CHANGELOG.rst, mds/apis/prv_api/event_records.py, mds/apis/prv_api/urls.py, mds/apis/schema.py, tests/apis/prv_api/test_event_records.py
So we can get, e.g., the last 5 events on a given device.
Had to tell the schema generator a ModelChoiceFilter is not a
ChoiceFilter...
=> Export (read only) event records

mds/server/settings.py, setup.cfg
When we go to the `Event Record` on the admin panel, we have a crash because of a missing template (postgis). Adding the application to fix this.
We fixed the versions of `djangorestframework==3.9.3` and `drf-yasg==1.16.0`, because there are still importing issues between the two due to the latest release of `djangorestframework (3.10.0)`.
This causes the error in this build: https://travis-ci.org/Polyconseil/django-mds/builds/562471386:
`
ImportError: Could not import 'drf_yasg.generators.OpenAPISchemaGenerator' for API setting 'DEFAULT_GENERATOR_CLASS'. ModuleNotFoundError: No module named 'packaging'.
`
=> Fix crash on event record admin panel

CHANGELOG.rst, mds/provider_poller/poller.py
This will enable to catch up some missed events in the past
with the `skip` query parameter.
=> Allow providers polling to be overriden

CHANGELOG.rst, mds/factories.py, tests/management/commands/test_poll_providers.py
The EventRecord factory may now generate Events with any id at anytime, with dates nearest to now.
=> Improvements on the EventRecord factory

CHANGELOG.rst, mds/apis/prv_api/provider_api.py
When we receive a "register" event, there is no associated `trip_id`. It crashed.
=> Provider API: fix nullable trip_id crash

CHANGELOG.rst, mds/apis/prv_api/provider_api.py, tests/apis/prv_api/test_status_changes.py
`register` events were mistakenly sent by our side of the "provider API" following https://github.com/Polyconseil/django-mds/commit/7f30193c478ac75c8c3b739a380fda7c73181a4a. Because we can receive `register` events by providers that use the "agency API"
=> Provider API: only send 'provider' events

CHANGELOG.rst, mds/apis/agency_api/v0_x/vehicles.py, tests/apis/agency_api/v0_x/test_devices.py
Goal: have the device_id in the error response when we push an event to a non-existant device.
```
{
"message": "No device found for device_id: aaaaaaaa-7bbe-430f-8043-a799d4574000",
"device_id": "aaaaaaaa-7bbe-430f-8043-a799d4574000"
}
```
=> Better response 404

mds/apis/agency_api/v0_x/vehicles.py, mds/server/settings.py, mds/utils.py, tests/apis/agency_api/v0_x/test_devices.py
This PR creates a settings and a function that'll need to be overriden to disable the registration of telemetries.
=> Add get_object_from_cache and use Settings to disable telemetry

.travis.yml
Make travis CI only launch one test run on Pull Request
- branch checks will only be run on master
- PR checks are left unchanged
=> Only run one CI for Pull Requests

CHANGELOG.rst, mds/enums.py, mds/locale/en_US/LC_MESSAGES/django.po, mds/locale/fr_FR/LC_MESSAGES/django.po
Those long explanations are better suited in a policy help text or
description.
And it seems like the locales haven't been updated in a long time...
You have to run "django-admin makemessages" from within the "mds"
folder.
=> enums: simpler naming of policy types

mds/enums.py
The functional API is not the canonical syntax, just a factory pattern.
=> enums: use the class API

CHANGELOG.rst, mds/enums.py, mds/provider_poller/poller.py, mds/provider_poller/settings.py, tests/management/commands/test_poll_providers.py
Closes: SMP-1362
If proven useless, remove them altogether.
=> poller: deactivate fake register events by default

mds/utils.py, tests/apis/agency_api/v0_x/test_devices.py
If you make it a module variable, it will be evaluated at import time.
`is_telemetry_enabled` was already treated as a function anyway.
Thus the monkey patch in the test becomes useless, the override_settings
works as expected.
=> utils: make is_telemetry_enabled lazy

CHANGELOG.rst, mds/provider_poller/poller.py
I think a MDS 0.4 server rejecting "application/json" is too strict, the
HTTP standard allows for multiple Accept values, the server just chooses
the first one that matches.
=> provider_poller: restore the expected behaviour for 0.4

CHANGELOG.rst, mds/apis/agency_api/v0_3/urls.py, tests/apis/agency_api/v0_3/test_devices.py
We should not require the urls to have a trailing slash
see
https://github.com/openmobilityfoundation/mobility-data-specification/tree/0.3.2/agency#vehicle---event
=> API Agency: autoriser le register de vehicles sur /vehicles, /event et /telemetry

mds/provider_poller/poller.py
It proved to be missing in production logs.
Also leave the f-strings although they don't play nice with the logging
API, but we can't use named interpolation, and a bunch of "%s" would be
a mess.
=> provider_poller: log provider being polled

mds/management/commands/poll_providers.py, mds/provider_poller/poller/translation.py, mds/provider_poller/poller/v0_2.py, mds/provider_poller/poller/v0_3.py, mds/provider_poller/poller/v0_4.py, tests/management/commands/test_poll_providers_v0_3.py, tests/management/commands/test_poll_providers_v0_4.py, tests/management/commands/utils.py
But reuse as much code as possible.
The goal is to avoid branching in the code to support multiple versions,
and regressions in other versions when we adjust the code for another
one.
Most of the benefit can be seen in forking the tests to covers all cases
with both versions.
Closes: SMP-1691
=> provider_poller: split into different implementations
