Polyconseil/django-mds

- midas/models.py
- midas/oas.yml
- midas/serializers.py
- midas/settings.py
- midas/templates/swagger.html
- midas/urls.py
- midas/views.py
J'ai mis ça sous `schema/` si ça cous va. Ce n'est pas parfait, mais ça marche ^_^
À terme je pense quand même qu'il faudra écrire (ou éditer) le yaml à la main pour faire un truc vraiment propre.
> swagger interface

- mds/factories.py
- tests/test_dbsetup.py
> Fix missing Polygon factory

- CHANGELOG.rst
- mds/apis/prv_api/service_areas.py
- mds/apis/prv_api/vehicles.py
- mds/apis/utils.py
Required to auto generate the schema.
> apis.utils: replace GeometryField by self documenting serializer.

- mds/apis/prv_api/service_areas.py
- tests/apis/prv_api/test_service_areas.py
Update PolygonRequest serializer to add areas missing field.
> Update PolygonRequest serializer and update tests

- mds/apis/prv_api/vehicles.py
- mds/apis/utils.py
- tests/apis/prv_api/test_vehicles.py
This forces swagger to generate Array types for MultipleChoiceFilter
> Fix swagger typings for multiple choice filters

- mds/apis/prv_api/authent.py
- mds/authent/public_api.py
One day authent endpoints may be outside mds.
> cleanly separate mds.authent from apis

- CHANGELOG.rst
- mds/apis/utils.py
- Fix swagger auto generation
- Create a specific filter class to allow comparison between two datetime ranges by overlap
> Fix handling of range filters

- mds/models.py
> models: Remove unused ProviderModel abstract class

- CHANGELOG.rst
- mds/management/commands/poll_providers.py
I also inverted latitude and longitude, once... or twice...
And a GeoJSON point could actually be in three components.
> poll_providers: more robust reading of coordinates

- mds/models.py
This will mostly serve in the Django admin.
Can't find anything relevant for EventRecord, without accessing related
device or provider.
> models: improve string representations

- mds/apis/agency_api/v0_x/vehicles.py
- tests/apis/agency_api/v0_x/test_devices.py
My first attempt only fixed the telemetry push, which is not part of the
specs.
Move validation to... the validator. The code I should have written in
the first place.
> agency_api: reuse GPS validation for event push

- mds/apis/agency_api/v0_x/vehicles.py
May seem obvious but tried to label main serializers (with a verb) and
subserializers (with a noun).
> agency_api: document vehicle serializers

- mds/apis/agency_api/v0_x/vehicles.py
- mds/db_helpers.py
- mds/management/commands/poll_providers.py
- mds/provider_poller/poller.py
- mds/utils.py
- tests/management/commands/test_poll_providers.py
So we benefit from the default values of the model, instead of copying
them, and a basic clean check.
> db_helpers: generalize upserting an unsaved model instance

- mds/db_helpers.py
This time I don't evade writing tests...
> db_helpers: fix upserting provider with non-null fields

- mds/apis/prv_api/provider_api.py
- mds/authent/migrations/0002_auto_20190124_0928.py
- mds/enums.py
- mds/factories.py
- mds/provider_mapping.py
- mds/provider_poller/poller.py
- tests/apis/prv_api/test_status_changes.py
- tests/management/commands/test_poll_providers.py
- tests/test_provider_mapping.py
Mapping was wrong, returning an invalid "trip" event type that does not exist in the provider API.
HB should also double-check the mapping
> Fix agency to provider event type mapping

- CHANGELOG.rst
- mds/enums.py
- mds/models.py
- tests/apis/agency_api/v0_x/test_devices.py
> Event type device status mapping

- CHANGELOG.rst
- mds/apis/agency_api/v0_x/policies.py
- mds/factories.py
- mds/models.py
- tests/apis/agency_api/v0_x/test_compliance.py
- tests/apis/agency_api/v0_x/test_policies.py
- tests/test_models.py
Changed the factory not to set an end date by default, which led to a
bigger diff than expected.
> models: unbound policies are active too

- CHANGELOG.rst
- mds/locale/fr_FR/LC_MESSAGES/django.po
"Ailleurs" to "Hors périmètre"
> Changing the French translation for "Elsewhere"

- README.md
- manage.py
- setup.cfg
- tests/conftest.py
- tests/project/settings.py
- tests/project/wsgi.py
We use this pattern in other of our libraries.
> tests: turn useless server into a test project

- mds/apis/agency_api/v0_x/vehicles.py
- mds/enums.py
- mds/provider_poller/poller.py
The first commit is just clean up, and should be read separately.
> read the expected MDS version, don't guess it

- mds/db_helpers.py
- mds/enums.py
- mds/factories.py
- mds/models.py
- mds/provider_poller/poller.py
- mds/provider_poller/settings.py
- mds/provider_poller/translation.py
- tests/management/commands/test_poll_providers.py
> poller: add MDS 0.4 support

- CHANGELOG.rst
- mds/provider_poller/poller.py
> provider_poller: restore backwards compatibility

- mds/provider_poller/poller.py
- tests/management/commands/test_poll_providers.py
As the poller is starting from the last event_time, we were polling the
same hour again and again.
> provider_poller: fix polling the next hour of archives

- mds/apis/agency_api/v0_4/urls.py
- mds/apis/agency_api/v0_4/utils.py
- mds/apis/agency_api/v0_4/vehicles.py
- mds/urls.py
- tests/apis/agency_api/v0_4/test_compliance.py
- tests/apis/agency_api/v0_4/test_geographies.py
- tests/apis/agency_api/v0_4/test_policies.py
- tests/apis/agency_api/v0_4/test_schema.py
- tests/apis/agency_api/v0_4/test_vehicles.py
The biggest part is the generic error messages. We lose information
compared to DRF doing the job.
And dropping the service_areas endpoint.
Fork the whole test suite to make sure the whole API is covered.
> agency_api: implement 0.4 with just what changes

- mds/provider_poller/poller.py
- tests/management/commands/test_poll_providers.py
It's still up to the provider to paginate results, so just send "now"...
Closes: SMP-1728
> provider_poller: "end_time" is mandatory in 0.4
